<?php

function cards_menu() {
    $friends = array("Dave", "Bave", "Cave");
    $items = array();

    for($i = 0; $i < count($friends); $i++){
        $items[$friends[$i]] = array(
            'title' => "Greetings $friends[$i]!",
            'page callback' => 'greeting_card',
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );
    }
    return $items;
}

function greeting_card() {
  return ' <p>Hello there!</p>';
}
